///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesDashboard = 'assets/images/dashboard.svg';
  static const String imagesLibrary = 'assets/images/library.svg';
  static const String imagesMore = 'assets/images/more.svg';
  static const String imagesWatch = 'assets/images/watch.svg';
}
